language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip
    - go: 1.4

install:
   - go get github.com/axw/gocov/gocov github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/pierrre/gotestcover github.com/Masterminds/glide
   - go get -t -d ./...

script:
  - go vet -x $(go list ./... | grep -v /internal/ | grep -v /vendor/)
  # - golint .
  - gotestcover -coverprofile="cover.out" -race -covermode="count" ./...
  - goveralls -coverprofile="cover.out"
